name: yagpdb build
run-name: yagpdb (via ${{ github.event_name }})

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

  workflow_dispatch:
    inputs:
      force-push:
        description: "push to GHCR"
        type: boolean
        required: true
        default: false

  pull_request:
    paths:
      - "docker/*"
      - "docker-bake.hcl"
      - ".github/workflows/build-push.yml"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  YAGPDB_REF: master
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: yagpdb
  IMAGE_PLATFORMS: "linux/amd64"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout YAG sources
        id: checkout-yag
        uses: actions/checkout@v3
        with:
          repository: botlabs-gg/yagpdb
          ref: ${{ env.YAGPDB_REF }}
          path: yagpdb
          submodules: recursive

      - name: Get YAG tag
        id: tagger
        working-directory: yagpdb
        run: |
          echo "tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.IMAGE_PLATFORMS }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=yashdbci
            org.opencontainers.image.description=Yet Another Self Hosted Discord Bot Docker Image
            org.opencontainers.image.vendor=neggles.dev
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD-hhmm' tz='UTC'}}
            type=semver,pattern={{version}},value=${{ steps.tagger.outputs.tag }},enable={{is_default_branch}}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.tagger.outputs.tag }},enable={{is_default_branch}}
            type=semver,pattern={{major}},value=${{ steps.tagger.outputs.tag }},enable={{is_default_branch}}
            type=edge,branch=main
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Versioned Tags
        id: build-push
        uses: docker/bake-action@v3
        with:
          targets: default
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: ${{ contains(fromJSON('["push", "schedule"]'), github.event_name) || inputs.force-push }}
          set: |
            yagpdb.args.YAGPDB_REF=${{ steps.tagger.outputs.tag }}
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=min
